module.exports = [
  { symbol: "RELIANCE.NS", name: "Reliance Industries" },
  { symbol: "TCS.NS", name: "Tata Consultancy Services" },
  { symbol: "INFY.NS", name: "Infosys" },
  { symbol: "HDFCBANK.NS", name: "HDFC Bank" },
  { symbol: "ICICIBANK.NS", name: "ICICI Bank" },
  { symbol: "SBIN.NS", name: "State Bank of India" },
  { symbol: "KOTAKBANK.NS", name: "Kotak Mahindra Bank" },
  { symbol: "AXISBANK.NS", name: "Axis Bank" },
  { symbol: "HINDUNILVR.NS", name: "Hindustan Unilever" },
  { symbol: "ITC.NS", name: "ITC" },
  { symbol: "LT.NS", name: "Larsen & Toubro" },
  { symbol: "BAJFINANCE.NS", name: "Bajaj Finance" },
  { symbol: "BHARTIARTL.NS", name: "Bharti Airtel" },
  { symbol: "MARUTI.NS", name: "Maruti Suzuki" },
  { symbol: "HCLTECH.NS", name: "HCL Technologies" },
  { symbol: "ASIANPAINT.NS", name: "Asian Paints" },
  { symbol: "ULTRACEMCO.NS", name: "UltraTech Cement" },
  { symbol: "TITAN.NS", name: "Titan Company" },
  { symbol: "ONGC.NS", name: "Oil & Natural Gas Corporation" },
  { symbol: "POWERGRID.NS", name: "Power Grid Corporation" },
  { symbol: "NTPC.NS", name: "NTPC" },
  { symbol: "SUNPHARMA.NS", name: "Sun Pharma" },
  { symbol: "DRREDDY.NS", name: "Dr Reddy's Laboratories" },
  { symbol: "DIVISLAB.NS", name: "Divi's Laboratories" },
  { symbol: "CIPLA.NS", name: "Cipla" },
  { symbol: "BRITANNIA.NS", name: "Britannia Industries" },
  { symbol: "TATASTEEL.NS", name: "Tata Steel" },
  { symbol: "JSWSTEEL.NS", name: "JSW Steel" },
  { symbol: "M&M.NS", name: "Mahindra & Mahindra" },
  { symbol: "EICHERMOT.NS", name: "Eicher Motors" },
  { symbol: "HEROMOTOCO.NS", name: "Hero MotoCorp" },
  { symbol: "BAJAJ_AUTO.NS", name: "Bajaj Auto" },
  { symbol: "ADANIENT.NS", name: "Adani Enterprises" },
  { symbol: "ADANIPORTS.NS", name: "Adani Ports & SEZ" },
  { symbol: "COALINDIA.NS", name: "Coal India" },
  { symbol: "NESTLEIND.NS", name: "Nestle India" },
  { symbol: "HDFCLIFE.NS", name: "HDFC Life Insurance" },
  { symbol: "SBILIFE.NS", name: "SBI Life Insurance" },
  { symbol: "ICICIPRULI.NS", name: "ICICI Prudential Life" },
  { symbol: "TATAMOTORS.NS", name: "Tata Motors" },
  { symbol: "GRASIM.NS", name: "Grasim Industries" },
  { symbol: "UPL.NS", name: "UPL Ltd" },
  { symbol: "LUPIN.NS", name: "Lupin" },
  { symbol: "AUROPHARMA.NS", name: "Aurobindo Pharma" },
  { symbol: "PEL.NS", name: "Piramal Enterprises" },
  { symbol: "MANAPPURAM.NS", name: "Manappuram Finance" },
  { symbol: "BANDHANBNK.NS", name: "Bandhan Bank" },
  { symbol: "PNB.NS", name: "Punjab National Bank" },
  { symbol: "IDFCFIRSTB.NS", name: "IDFC First Bank" },
  { symbol: "FEDERALBNK.NS", name: "Federal Bank" },
  { symbol: "BANKBARODA.NS", name: "Bank of Baroda" },
  { symbol: "CANBK.NS", name: "Canara Bank" },
  { symbol: "INDUSINDBK.NS", name: "IndusInd Bank" },
  { symbol: "YESBANK.NS", name: "YES Bank" },
  { symbol: "LICI.NS", name: "Life Insurance Corporation" },
  { symbol: "TATAPOWER.NS", name: "Tata Power" },
  { symbol: "DLF.NS", name: "DLF Ltd" },
  { symbol: "GAIL.NS", name: "GAIL India" },
  { symbol: "BPCL.NS", name: "Bharat Petroleum" },
  { symbol: "IOC.NS", name: "Indian Oil Corporation" },
  { symbol: "HAVELLS.NS", name: "Havells India" },
  { symbol: "PIDILITIND.NS", name: "Pidilite Industries" },
  { symbol: "JSWENERGY.NS", name: "JSW Energy" },
  { symbol: "LTIM.NS", name: "LTI Mindtree" },
  { symbol: "TECHM.NS", name: "Tech Mahindra" },
  { symbol: "WIPRO.NS", name: "Wipro" },
  { symbol: "MUTHOOTFIN.NS", name: "Muthoot Finance" },
  { symbol: "TATACONSUM.NS", name: "Tata Consumer Products" },
  { symbol: "COLPAL.NS", name: "Colgate-Palmolive India" },
  { symbol: "PAGEIND.NS", name: "Page Industries" },
  { symbol: "DABUR.NS", name: "Dabur India" },
  { symbol: "HINDALCO.NS", name: "Hindalco Industries" },
];

